apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
- ./ingress.yaml
- ./default-resource.yaml
- ./s3-backup-daily-recurring-job.yaml
generators:
- ./secret-generator.yaml
