apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qbt
resources:
  - ./namespace.yaml
  - ./qbt-service.yaml
  - ./qbt-endpointslice.yaml
  - ./qbt-ingress.yaml
  - ./bazarr-service.yaml
  - ./bazarr-endpointslice.yaml
  - ./bazarr-ingress.yaml
  - ./radarr-service.yaml
  - ./radarr-endpointslice.yaml
  - ./radarr-ingress.yaml
  - ./sonarr-service.yaml
  - ./sonarr-endpointslice.yaml
  - ./sonarr-ingress.yaml
