apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: admin
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: admin
    spec:
      containers:
        - image: chrislusf/seaweedfs:4.04
          name: admin
          args:
            - admin
            - "-port=23646"
            - "-masters=master:9333"
            - "-adminUser=admin"
            - "-adminPassword=password123"
            - "-dataDir=/data"
          ports:
            - containerPort: 23646
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: admin-data
