apiVersion: v1
kind: Secret
type: Opaque
metadata:
    annotations:
        use-subpath: "true"
    labels:
        io.kompose.service: filer
    name: s3-config
stringData:
    s3.json: ENC[AES256_GCM,data:Qftj6D34UhhxljDmxmXjDvZwGyrR1UrV48p8uCvznOapFGkhZM+4Gcvl8mxpQuUbL1i1U6lYTjj0HaQbRi6foMfst+VnMoz2uAUJbqNUKc/9p4pPKL/QPZaSPkor9lh6LLBVpwEw8HcnJ4UdFAvt6Y5SlWQU4u+mgBGK98JH6y/utrbmOQ8ey3aZQ2Uobxw33fR+gZn3IttlNWyEVDdSqqvKNx8jPJSJhB10TXqGKXwIl+U6oQqxprn/+f21lSxQUMrzBqTjMTkoreNHRKuGK40rcZ81E/RRnTL7hqc97RApKZxaJdOwD12p1F2597EE4vScCFCXUgqfGEfOretJEXvsUJVDXfGA2fLj9rmsAvTFHG8tI2xWZMuYa4BNtij0d+hMuXVEVIZ6/Xh40HF+ZmPmp8MuNLYaVeyH1wrFxVOtocWq6/a9t0FNUByhavX1+FWbRyH1FzUGNJukrPVcRns4fZZv2uBlJGLBz4cO9Bq7nlMdSW8Djtdoz39XUn/ehmr+efHoz84yeL8a6V1rd/jExsH56ltwRZ8L/ZSW8uy1HgGt6S5Ykubfg41eBGXONQ2KE2bRYW83Uqw3DmbVudxQeM2c+bGBMno04hngOqL2PPjPcUYQ3kRLD0qwwlfn1+UxeXu1ngy2iM1G9+FSVpJ4nGc5nDsIl14fRb7vkpnmBdPqIw52dC6j4QAkjrMyw8w2DHMLTmGkCzqgnYmTo0Tge9PiagBa6ue6nuCYP3pg3ZVkSQO0V6Sxj/gLBfFT7Blu3l+9oIOEnHC3+5NweqtpYHWQTKbKezOMYud8UyjByUwhgNQuM4Aqiju8FmbLuPAV4YGQ6z59vNausRQDQdSMxuG+IqRep6eGXA7pY7nrnlDjnJpP84J7xhPlZlvyAAP+VrVH7WNKryODbrJGnJBYl1JNGY8Uipa3yruRB2xpkk2jXqW6xFPsg1r7+0eLB4GSE8wNrvzZTUfMckNr9IQkD6B2FGupZA+wXVCTyHPuaLsZM5kjFXA803/Oav+72c46iKKcOlGGOfWrnRrtWI2600bhUDtIipL4Fp0IEreiwACztuMjkXNuzuHOEU1IHeblD6MFKiC4J5bxNxDBo2I0UkR2AoSEg2u7q1uSLBf4DthpJS8iHECmjsXp8Kkk+QVRuqC4r0ibkB9EGNq7mNPDm7xKJRPscGm7UtfJTUZhJSecW8q+2ihegPdN6a+IzrZSC3Qh+hMSHbhbewif8ynBXWWH4HB7AEBQskAjTB79s9k068ObmjGATTHwa8OiYmFE7OviEvKJlCfTpgeYV9pqZ8l3WXhGdxZ0L1QiXd2kHiYhv3ZcTXvwmQW8hxfeAs7ryWxaf/c/yQEM2DAvsbgXZY387cC1dzgRTd5XNVQ=,iv:EbwDA198odxY90dLpM2bF0U5NqWAZqJi3ZJ4SlTaROY=,tag:NJJ3woKuh9uThrWCCNTCmg==,type:str]
sops:
    age:
        - recipient: age1fs9c9xejszarcv6c3r62efnkny06yvl6zgjlhemmyvyd2t8zq40sqtnpvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYXZpQXdRK250UGVacTY1
            RUtOUVR4UkU4QTNkTnhWOERicXN2T1ozcFVBCllsSU0zQStPWDAwWnc1Y2w1M3ox
            ODdGSTlrS2tUakl6V2FkRXBoNHRnREUKLS0tIEZFRDQ5QWkyeUczMEVFMk5zRXZw
            YUtEMUNwbitRdDFzdU5NczJXOGR0bGMKNKC583OIDyKWJiHhYm8Za+qhTwnW3uoq
            8jR5aLlZOru98Pc3WVVbZu+dX64ws89YoiOV9DIosKm3IPK+K9RBYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T16:25:04Z"
    mac: ENC[AES256_GCM,data:/DsnLWAiIq0i87dabEqY1yGNYVyLwphBoGR6D+JrNs4IIwIFJyG8o+lMtL7J67gD4r+uSziFBrh4iamdoQytjejUH/wnjLI0NNiHov9oCPeIlVxjZfI9gGfI2kVu3WJs2LztmCuPPoVlnfk9nS3U2y9dGrhc886I8xTF90gK1Xo=,iv:ptIm9kzx+MsGIzzzcMq49lVdxRCJ6AXWc5DpPFGSvCM=,tag:7EFlx12e0G3xp+WOy4Hfuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
