apiVersion: v1
kind: Secret
type: Opaque
metadata:
    annotations:
        use-subpath: "true"
    labels:
        io.kompose.service: filer
    name: s3-config
stringData:
    s3.json: ENC[AES256_GCM,data:MxDjB26jtBaxkCuWc7WrT8sD9enfvZUB72A1PgECZuOHGBDWJG8pcAQmScA7COpW2jVexBIa9xyZ/TNJ/h9jnM/wAn977sDDmpozRgVW90qvauN3Ls/WCH/6dHYwhHDDUIgnEJFko++Zmc1ZI9CYuW8ynK9GnUmbVycOoRhX1jseutUgR2HJyCHhWWFfdzuVtB0TVygGdBPsaVWpqxg7cGkcisHud6iimdpsst+bzLK8YkyvAaK432YdbshK761bow/EGZJWmiWnl5ExtGYZX/SyrqEWfShk0LlPJLDE2lB3okEdfn6vbMe7AYEi9z5G7nbZBC9PGilP1Un4fO9D/cvmohrmlRjlO2S8KkHfgzu+7Kr0ldygOHTuJakPvKuLUzHd5nt3Gr772+NTwnqA5va9lE7fe+WdnCwZwW+YGSIduCk3CNGyKQzsu3mN0knXPimHatK0Y62VqYPY2MF2BeAPQFHdkZZFYevJr9FzsOC4aF3+U+K6K69xh5ZXtcFQQflADn0UxRoOPAKM/avUXGjTeR+DjKiplj7pZVq/C2ydVOk7Jim3l8WnJtkAJaFw29P549y/g30Gx3v94RYV3qdq6hhFWzsx+F1OreGF3Cl9APSy7q77d8jOszo71KBLbH8f8305/05NkCvmrpcxbkJsLAQU7kiRgDl5FcX/mATbCsOhtEU/ULN/yjpY9fXQiYwNHhkwRt73+oeRsTc3D0tSbcZsf0FGmyZ2lYl/Dep8e2OLbDDfqtk2ltsRPegG/8opvY9JLj+pO67pCDV865UawPjdVapxoS9IQKMiyhn5uQ3trbKKVPXipyM7kh1rXQI8HdpXMXFKQGG4C4RRJCqxOS9M7DLOvypFXwAlQ96NjNOpAr8bEO9s50gcQK6eIkaOBKrMseRxAlKbO4kflQlRBWnyWk01FJyzhG+AMr+nB+IOZV77aDDoonf2pJCSdUWg/8BoB/6OazdyfpuYAmCzJo3mJ2s0HvQOiJj4pDzTgKI6Fvg+EArpleQobzKoujdndaZy92NSgOjQjnvDKe9KkgQDCON3UK6sJaQK7rYCBTZvzA96VIB2kuuXBQxyK/m0h/R4CPtmcMab8D3ZUbvGRzpIy2CNQmNSh1RXxymkCQPbSLjWkltAVjigx3XkKIF4fupAXfZgdfpQr3TGjYHIXjbAgx1l3QITNmuv5N/4VkQzsV7V07Z/4H5FRGBo7qg4hXJOjJvG3Xi+jBSlo5QGkwI+JX/6ScVI1J0FpQg/D0YO9pt4cpAL5cRw2CAdA4l858TrEvN0Xdt/iwnGj1DOA27ngK3nk1qf6k0uqk97itA4gFlxaAQIy/OvGqAREyuJVHxHP3/KThARdym0p5EoRXBf9aCBSEVb2YilcejeEMi5UMJ0IPJtqP+p3/KpxBnhg1XbSMojqm3emjXeKFbHn79HtBxyRrKPluoq0g+YBVqvgeIqYMw45ApOIXk0eYaFBF5ykDrvZ34DRKT97NVocodSPlo7Cq44mwltf64H9rEr8BED6WS0/ee0K1J0oDFuzf/GDg7u6nL/XP/ha4pXjpLDHHRlRzSoww+yYmZG+ZYrXHyVKUFxrk/tZPTmbwKj/YsayNnhlgxXCZrDQ0zbQBKRHq3SKfvHNElPg52xJieSR8R6o5E75Co7fqx+kogAyjk0hzYGm7G9XJvAYvZol/dIE3tJ7yecwd2ArU44Z49H8wogZit0CR+/QhERgkenQzB+gT1cGO6DB8X1Wqfj84pz3YNsQbPtwG6JXTl+XJWVCgxAZggdKdO+TbuoxSioJ4vKq3WR1Uw7Ut/JMTiSogrEoA/zTn7fcPIPcjJaiehV6++FvpcONNT4bDNhf71QTqvh1Vc=,iv:kfza2e0ZcY0+4QFHSjcFaK1anKnb4KiVaUevrsfZw+0=,tag:wJZaM3+yQFsD6hZBCyD/HA==,type:str]
sops:
    age:
        - recipient: age1fs9c9xejszarcv6c3r62efnkny06yvl6zgjlhemmyvyd2t8zq40sqtnpvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYXZpQXdRK250UGVacTY1
            RUtOUVR4UkU4QTNkTnhWOERicXN2T1ozcFVBCllsSU0zQStPWDAwWnc1Y2w1M3ox
            ODdGSTlrS2tUakl6V2FkRXBoNHRnREUKLS0tIEZFRDQ5QWkyeUczMEVFMk5zRXZw
            YUtEMUNwbitRdDFzdU5NczJXOGR0bGMKNKC583OIDyKWJiHhYm8Za+qhTwnW3uoq
            8jR5aLlZOru98Pc3WVVbZu+dX64ws89YoiOV9DIosKm3IPK+K9RBYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T16:25:31Z"
    mac: ENC[AES256_GCM,data:jgK2MK6UTNMR/GhJ25HpJ2n1IHbWzTj9lxP0VgwMU2OVtHlsP+KZLqnh7RTN0f1pLj3ZZQ+qKdKMrGw59WofKUNHxI9b58/Ltl+sY4Cl4+vD265+5hrGMseAnvF+kv4EFNskb/Rmmq1qGkU48RhGuYDnoSa4oYT4pUV4Gay6oHM=,iv:Tr/9964sniZxMKY4S5kr+huWlwzUPcAtcNIUUWBiQfU=,tag:NG+SEiqZWWXbSkb2xIMrWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
