apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seaweedfs
resources:
- ./namespace.yaml
- ./master-service.yaml
- ./master-deployment.yaml
- ./volume-service.yaml
- ./volume-stateful-set.yaml
- ./filer-config-map.yaml
- ./filer-data-pvc.yaml
- ./filer-service.yaml
- ./filer-deployment.yaml
- ./admin-data-pvc.yaml
- ./admin-service.yaml
- ./admin-deployment.yaml
- ./admin-ingress.yaml
generators:
- ./secret-generator.yaml
