all:
    hosts:
        mini:
            ansible_host: mini
            ansible_user: root
            letsencrypt_email: ENC[AES256_GCM,data:L5ZbXmZb5mVLMN+F+wey0ja9c8G3l1MsJI9GR2XJW5Oy,iv:5vXr5VxU1XZj++0/Df6BUhsL3e5NZPGPvjMdyz3QagM=,tag:KIsOf3zbYlzSJC2srQvXng==,type:str]
            certbot_domains:
                - ENC[AES256_GCM,data:zd2jKPDbNaBeXMIbssbU,iv:ak8pVs5HB2dcz7NqiK261mks8Ua12KgCXtUrlkkiwMM=,tag:bWV0sQEpXOYf3Wyt7hIMyA==,type:str]
                - ENC[AES256_GCM,data:ltndFaCy227jZ2w83rxhdw==,iv:QrJwy6c8/8EVOXZIhgiNM7uUAkNm2Tc2GFqRKEdS72Y=,tag:LjMzULx1S/YqPr85yEi6qA==,type:str]
sops:
    age:
        - recipient: age1fs9c9xejszarcv6c3r62efnkny06yvl6zgjlhemmyvyd2t8zq40sqtnpvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMEtGMU93TFFyOCthcFhY
            a29YYTlCTnVtdUpjM2x0RExsVGQxdjhONGx3Cm5TbGRsSjdIVzBBbFAraG9BZWNs
            Nkl6OWhUbW5uaWJJeW52eTFwL3p1Q28KLS0tIHNxODNuemhRTGxNSlhrOE1hWTY2
            VkdOL3pyV2loVHMwa0tXRWpGVGtqUlEK5GxPsA3U4WMPe49QxzBawa1q2mzuVDyD
            VqGz49gwVqKqYmTK3+SeVRzTrKSaJ4+cNUJKuh5oc0fVNlJMQDDrfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T23:17:17Z"
    mac: ENC[AES256_GCM,data:xiOXUrEe/dPnyjW6ZYLhZdAqyEDDr0gz80q38QIZavS5cfEj3Z8ath1h77hL1ow2HeiTK5w+4SGK/bXecxtizDrvKZ63nlYq/a3zXN69y20SUQ3YFGGoncO1Hv6gpWcU9TIDtForxFGZ2yUGp/Lv7TTfkGORjHHEE6b3qhL0XOs=,iv:Qxc6/XgqtWg9AGIKPb84DQKLXhevjksdRy3QAC5RS9I=,tag:LJTpQ6g5hsJ1UGEKGDAIZg==,type:str]
    encrypted_regex: ^(letsencrypt_email|certbot_domains)$
    version: 3.11.0
