all:
    hosts:
        mini:
            ansible_host: mini
            ansible_user: root
            k8s_passthrough_domains:
                - ENC[AES256_GCM,data:JIlHw+jAWGiIYo35W78=,iv:IldOoYtrSy47vs0D+UEHjZ3wM/InfwDb5IfDPkrhFtU=,tag:qMg28BlGqgqVe3i8cAHkpg==,type:str]
                - ENC[AES256_GCM,data:65Iv4gsDq2lijOHvIlqf6Q==,iv:3pCZAIydAQr4bgzczRiZJNpG3mF8DIdBAkkkcMtRD9s=,tag:+FKTsYdUaQhSZU/9ll3sug==,type:str]
                - ENC[AES256_GCM,data:+lxUftiC9M+UwpMMWwLomQyt7A==,iv:xkG0JjjlzJPnP7AuLpgbnwB0riLI2hH68uhcijvF+QM=,tag:tk8S7ofsc5zgR+X8pr6ytw==,type:str]
                - ENC[AES256_GCM,data:g98bS0cp4/TFOb4UuROm,iv:nMNzNDLXF5qlBY9uco/JvrVjqioS3kwKc2p+VhdATF4=,tag:rOCjRfmXI4rK79w/Utn3Zw==,type:str]
                - ENC[AES256_GCM,data:Vd6DBWIocsnnvw==,iv:eQwTxRypjHoCWOCdZr3ZVO2/uJPTli7L1STqCMdeMBs=,tag:MihMQAqsV5ApkfBQUSps/A==,type:str]
sops:
    age:
        - recipient: age1fs9c9xejszarcv6c3r62efnkny06yvl6zgjlhemmyvyd2t8zq40sqtnpvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENHZucnNyR1VXS25RcVRq
            UnNOV1NmZXZqZFNSei9rWklHd2JYNjRaMzNZCk4yaFd4SnRnc21UdUkvRjJzWW1F
            VldrQktsN1MrQ3gzZ2RkWUFaUXNvcmMKLS0tIGhUS3VaUXZGYnE5QkFFUkRPTDJj
            Y3p1SjhFdHhNMlA3Ulo0TllmYWllN2sK/LxmIO2kYdPAEXWnH51zUvxhB53rgGur
            JooMOg+1tp10bICH4zMK5XnQKkg+CtmxuSW8235IeHwYI1yoeZeKUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T16:55:41Z"
    mac: ENC[AES256_GCM,data:fL4SKG8f0eyRCy1HGgSXyKqpbYkRFs1XD0EKIVEM4b3WNKta3LWHwbxBfUABxjWCH3rYh6kikUV730/d6cguuBy/fkWPYjvdWI5DPFJEeM7smcyyQtl1oyr5hgJFBYCGK3p/A0MA20LILlha+54XVmRjYDJ+IEXfVqW8xgZDOeA=,iv:IyD3iYLCt2QygAwlRREGC9qg10HbwBeHpMXGUYIItBs=,tag:0Aj8ZN8yd92y0arJXotH0Q==,type:str]
    encrypted_regex: ^(letsencrypt_email|certbot_domains|k8s_passthrough_domains)$
    version: 3.11.0
