apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: diun
  name: diun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diun
  template:
    metadata:
      labels:
        app: diun
      annotations:
        # watching on littlebox
        diun.enable: "false"
    spec:
      serviceAccountName: diun
      containers:
        - name: diun
          image: crazymax/diun:4.30.0
          args: ["serve"]
          envFrom:
            - secretRef:
                name: secret-notif
          env:
            - name: TZ
              value: "America/New_York"
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_JSON
              value: "false"
            - name: DIUN_WATCH_WORKERS
              value: "20"
              # fridays
            - name: DIUN_WATCH_SCHEDULE
              value: "0 0 * * 5"
              # only notify of new tags, not updates to tags
            - name: DIUN_DEFAULTS_NOTIFYON
              value: "new"
            - name: DIUN_PROVIDERS_KUBERNETES
              value: "true"
            - name: DIUN_PROVIDERS_DOCKER
              value: "false"
            - name: DIUN_WATCH_JITTER
              value: "30s"
            - name: DIUN_WATCH_FIRSTCHECKNOTIF
              value: "false"
            - name: DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT
              value: "false"
          volumeMounts:
            - mountPath: "/data"
              name: "data"
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-lh
