all:
  children:
    k3s_lbs:
      hosts:
        cary:
          ansible_host: 192.168.1.100
          ansible_user: root
          vrrp_state: MASTER
          vrrp_priority: 200
        mini:
          ansible_host: 192.168.1.94
          ansible_user: root
          vrrp_state: BACKUP
          vrrp_priority: 100
    k3s_servers:
      hosts:
        cary:
          ansible_host: 192.168.1.100
          ansible_user: root
        mini:
          ansible_host: 192.168.1.94
          ansible_user: root
        littlebox:
          ansible_host: 192.168.1.217
          ansible_user: root
